name: if test
run-name: ${{ github.actor }} if test
on: [workflow_dispatch]
# env:
#   # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#   GH_TOKEN: ${{ secrets.MY_TEST_TOKEN }}

jobs:
  if-test:
    runs-on: ubuntu-latest
    env:
      VAR: true
    steps:
      - run: echo $VAR
      - name: if true
        if: $VAR = "true"
        run: echo "run true"
      - name: if false
        if: $VAR != "true"
        run: echo "false"
