name: Example Workflow
on:
  push:
    branches:
      # - main
      - workflow_dispatch
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get -y install jq

      - name: Run gh project list command and capture output
        id: gh_project_list
        run: |
          # gh project listコマンドを実行し、その結果を変数に格納
          gh_project_list=$(gh project list --json)
          echo "::set-output name=gh_project_list::$gh_project_list"
          
      - name: Use gh project list output
        run: |
          # スクリプト内でJSONパースしてデータを抽出
          gh_output="${{ steps.gh_project_list.outputs.gh_project_list }}"
          project_names=$(echo "$gh_output" | jq -r '.[].name')
          echo "GitHub Projects in the repository:"
          echo "$project_names"
        shell: bash
        # jqコマンドを実行するためにjqパッケージをインストール
        env:
          DEBIAN_FRONTEND: noninteractive
