name: Merge release note test
run-name: ${{ github.actor }} Merge release note test
on: [workflow_dispatch]
env:
  # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.MY_TEST_TOKEN }}

jobs:
  merge-release-notes-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/v##g")
          echo $VERSION
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Set up JDK 8 and 11 (default 8)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: |
            11
      - name: checkout release note scripts
        uses: actions/checkout@v4
        with:
          repository: reddikih/release-note-script
          token: ${{ secrets.MY_TEST_TOKEN }}
          path: ${{ github.workspace }}
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            src/main/java
      - name: Move scripts to the working directory
        run: cp ${{ github.workspace }}/src/main/java/* ${{ github.workspace }}
      - name: Checkout the ScalarDB's release notes
        run: |
          gh release view v0.0.1 --repo reddikih/dummy-scalardb --json body -q .body > scalardb.md
          gh release view v0.0.1 --repo reddikih/dummy-scalardb-cluster --json body -q .body > cluster.md
          gh release view v0.0.1 --repo reddikih/dummy-scalardb-graphql --json body -q .body > graphql.md
          gh release view v0.0.1 --repo reddikih/dummy-scalardb-sql --json body -q .body > sql.md
      - name: Create merged release note
        id: rn_body
        run: |
          java --source 11 MergeReleaseNotes.java scalardb.md cluster.md graphql.md sql.md > rnbody.md
          echo "rnbody<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat rnbody.md)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.rn_body.outputs.rnbody }}
          draft: true
          prerelease: false
