name: Merged release note test
run-name: ${{ github.actor }} Merged release note test
on: [workflow_dispatch]
env:
  # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.MY_TEST_TOKEN }}

jobs:
  release-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8 and 11 (default 8)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: |
            11
      - name: checkout release note scripts
        uses: actions/checkout@v4
        with:
          repository: reddikih/release-note-script
          token: ${{ secrets.MY_TEST_TOKEN }}
          path: ${{ github.workspace }}
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            src/main/java
      - name: Move scripts to the working directory
        run: cp ${{ github.workspace }}/src/main/java/* ${{ github.workspace }}
      - name: Checkout the ScalarDB's release notes
        run: |
          gh release view v0.0.1 --repo reddikih/dummy-scalardb --json body -q .body > scalardb.md
          cat scalardb.md
