name: release note test
run-name: ${{ github.actor }} release note test
on: [workflow_dispatch]
env:
  # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.MY_TEST_TOKEN }}

jobs:
  release-test:
    runs-on: ubuntu-latest
    # permissions: read-all
    steps:
      - name: Set up JDK 8 and 11 (default 8)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: |
            11
            8
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: checkout release note scripts
        uses: actions/checkout@v4
        with:
          repository: reddikih/release-note-script
          token: ${{ secrets.MY_TEST_TOKEN }}
          path: ${{ github.workspace }}
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            src/main/java
      - name: Move scripts to the working directory
        run: cp ${{ github.workspace }}/src/main/java/* ${{ github.workspace }}
      - name: JDK version check
        run: $JAVA_HOME_11_X64/bin/java -version
      - name: run release note script
        id: rn_body
        run: |
          $JAVA_HOME_11_X64/bin/java --source 11 ReleaseNoteCreation.java reddikih ScalarDB 1.0.0 mytest > rnbody.md
          echo "rnbody<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat rnbody.md)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.rn_body.outputs.rnbody }}
          draft: true
          prerelease: false
