name: release note test
run-name: ${{ github.actor }} release note test
on: [workflow_dispatch]
env:
  GH_TOKEN: ${{ secrets.MY_TEST_TOKEN }}
  # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release-test:
    runs-on: ubuntu-latest
    # permissions: read-all
    steps:
      - name: Set up JDK 8 and 11 (default 8)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: |
            11
            8
      - uses: actions/checkout@v4
      - name: JDK version check
        run: $JAVA_HOME_11_X64/bin/java -version
      - name: run release note script
        run: |
          $JAVA_HOME_11_X64/bin/java --source 11 ReleaseNoteCreation.java reddikih ScalarDB 1.0.0 mytest > mytest.md
          RN_BODY=$(cat mytest.md)
      - name: show release note
        run: cat mytest.md

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: $RN_BODY
          draft: true
          prerelease: false
