name: release note test
run-name: ${{ github.actor }} release note test
on:
  workflow_dispatch:
  workflow_run:
    workflows: [trigger-workflow]
    types:
        - completed

jobs:
  release-note-creation-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8 and 11 (default 8)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: |
            11
            8
      - name: Checkout the current repository
        uses: actions/checkout@v4
      - name: checkout release note scripts
        uses: actions/checkout@v4
        with:
          repository: reddikih/release-note-script
          token: ${{ secrets.MY_TEST_TOKEN }}
          path: ${{ github.workspace }}
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            src/main/java
      - name: Move scripts to the working directory
        run: cp ${{ github.workspace }}/src/main/java/* ${{ github.workspace }}
      - name: JDK version check
        run: $JAVA_HOME_11_X64/bin/java -version
      - name: run release note script
        id: rn_body
        env:
          GH_TOKEN: ${{ secrets.MY_TEST_TOKEN }}
        run: |
          $JAVA_HOME_11_X64/bin/java --source 11 ReleaseNoteCreation.java ${{ github.repository_owner }} ScalarDB ${{ steps.version.outputs.version }} ${{ github.event.repository.name }} > rnbody.md
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: rnbody.md
          draft: true
          prerelease: false
