# Test
name: run-by-manually-test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch]
# env:
#     GH_TOKEN: ${{ github.token }}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: std output test
        shell: 'script -q -e -c "stty cols 200 rows 100; bash {0}"'
        run: gh project list --owner reddikih
      # This doesn't show any output because GitHub Actions doesn't provide stdout by default.
      # - name: gh auth test
      #   # shell: 'script -q -e -c "stty cols 200 rows 100; bash {0}"'
      #   run: gh auth token
      - name: gh auth test 1
        # shell: 'script -q -e -c "stty cols 200 rows 100; bash {0}"'
        run: gh auth token > output 2>&1
      - name: gh auth test 2
        run: result=$(cat output);echo $result

  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Shell Command and Capture Output
        id: shell_command
        run: |
          # シェルコマンドを実行し、その結果を変数に格納
          result=$(echo "Hello, World!")
          echo "result=$result" >> $GITHUB_OUTPUT  # 出力をGitHub Actionsの出力にセット
      - name: Use Shell Command Output
        run: |
          # スクリプト内で変数を使用して結果を表示
          output="${{ steps.shell_command.outputs.result }}"
          echo "The result is $output"
