# Test
name: run-by-manually-test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch]
env:
    GH_TOKEN: ${{ github.token }}
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: std output test
        shell: 'script -q -e -c "bash {0}"'
        run: gh project list --owner reddikih
