# Test
name: run-by-manually-test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch]
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello world!
      - run: gh project list --owner reddikih
